module.exports = {
  Alabama: { abbreviation: "AL" },
  Alaska: { abbreviation: "AK" },
  Arizona: { abbreviation: "AZ" },
  Arkansas: { abbreviation: "AR" },
  California: { abbreviation: "CA" },
  Colorado: { abbreviation: "CO" },
  Connecticut: { abbreviation: "CT" },
  Delaware: { abbreviation: "DE" },
  "District of Columbia": { abbreviation: "DC" },
  Florida: { abbreviation: "FL" },
  Georgia: { abbreviation: "GA" },
  Hawaii: { abbreviation: "HI" },
  Idaho: { abbreviation: "ID" },
  Illinois: { abbreviation: "IL" },
  Indiana: { abbreviation: "IN" },
  Iowa: { abbreviation: "IA" },
  Kansas: { abbreviation: "KS" },
  Kentucky: { abbreviation: "KY" },
  Louisiana: { abbreviation: "LA" },
  Maine: { abbreviation: "ME" },
  Maryland: { abbreviation: "MD" },
  Massachusetts: { abbreviation: "MA" },
  Michigan: { abbreviation: "MI" },
  Minnesota: { abbreviation: "MN" },
  Mississippi: { abbreviation: "MS" },
  Missouri: { abbreviation: "MO" },
  Montana: { abbreviation: "MT" },
  Nebraska: { abbreviation: "NE" },
  Nevada: { abbreviation: "NV" },
  "New Hampshire": { abbreviation: "NH" },
  "New Jersey": { abbreviation: "NJ" },
  "New Mexico": { abbreviation: "NM" },
  "New York": { abbreviation: "NY" },
  "North Carolina": { abbreviation: "NC" },
  "North Dakota": { abbreviation: "ND" },
  Ohio: { abbreviation: "OH" },
  Oklahoma: { abbreviation: "OK" },
  Oregon: { abbreviation: "OR" },
  Pennsylvania: { abbreviation: "PA" },
  "Rhode Island": { abbreviation: "RI" },
  "South Carolina": { abbreviation: "SC" },
  "South Dakota": { abbreviation: "SD" },
  Tennessee: { abbreviation: "TN" },
  Texas: { abbreviation: "TX" },
  Utah: { abbreviation: "UT" },
  Vermont: { abbreviation: "VT" },
  Virginia: { abbreviation: "VA" },
  Washington: { abbreviation: "WA" },
  "West Virginia": { abbreviation: "WV" },
  Wisconsin: { abbreviation: "WI" },
  Wyoming: { abbreviation: "WY" },
};
