module.exports = {
  Alabama: { slug: 'alabama', abbreviation: 'AL' },
  Alaska: { slug: 'alaska', abbreviation: 'AK' },
  Arizona: { slug: 'arizona', abbreviation: 'AZ' },
  Arkansas: { slug: 'arkansas', abbreviation: 'AR' },
  California: { slug: 'california', abbreviation: 'CA' },
  Colorado: { slug: 'colorado', abbreviation: 'CO' },
  Connecticut: { slug: 'connecticut', abbreviation: 'CT' },
  Delaware: { slug: 'delaware', abbreviation: 'DE' },
  'District of Columbia': { slug: 'district-of-columbia', abbreviation: 'DC' },
  Florida: { slug: 'florida', abbreviation: 'FL' },
  Georgia: { slug: 'georgia', abbreviation: 'GA' },
  Hawaii: { slug: 'hawaii', abbreviation: 'HI' },
  Idaho: { slug: 'idaho', abbreviation: 'ID' },
  Illinois: { slug: 'illinois', abbreviation: 'IL' },
  Indiana: { slug: 'indiana', abbreviation: 'IN' },
  Iowa: { slug: 'iowa', abbreviation: 'IA' },
  Kansas: { slug: 'kansas', abbreviation: 'KS' },
  Kentucky: { slug: 'kentucky', abbreviation: 'KY' },
  Louisiana: { slug: 'louisiana', abbreviation: 'LA' },
  Maine: { slug: 'maine', abbreviation: 'ME' },
  Maryland: { slug: 'maryland', abbreviation: 'MD' },
  Massachusetts: { slug: 'massachusetts', abbreviation: 'MA' },
  Michigan: { slug: 'michigan', abbreviation: 'MI' },
  Minnesota: { slug: 'minnesota', abbreviation: 'MN' },
  Mississippi: { slug: 'mississippi', abbreviation: 'MS' },
  Missouri: { slug: 'missouri', abbreviation: 'MO' },
  Montana: { slug: 'montana', abbreviation: 'MT' },
  Nebraska: { slug: 'nebraska', abbreviation: 'NE' },
  Nevada: { slug: 'nevada', abbreviation: 'NV' },
  'New Hampshire': { slug: 'new-hampshire', abbreviation: 'NH' },
  'New Jersey': { slug: 'new-jersey', abbreviation: 'NJ' },
  'New Mexico': { slug: 'new-mexico', abbreviation: 'NM' },
  'New York': { slug: 'new-york', abbreviation: 'NY' },
  'North Carolina': { slug: 'north-carolina', abbreviation: 'NC' },
  'North Dakota': { slug: 'north-dakota', abbreviation: 'ND' },
  Ohio: { slug: 'ohio', abbreviation: 'OH' },
  Oklahoma: { slug: 'oklahoma', abbreviation: 'OK' },
  Oregon: { slug: 'oregon', abbreviation: 'OR' },
  Pennsylvania: { slug: 'pennsylvania', abbreviation: 'PA' },
  'Rhode Island': { slug: 'rhode-island', abbreviation: 'RI' },
  'South Carolina': { slug: 'south-carolina', abbreviation: 'SC' },
  'South Dakota': { slug: 'south-dakota', abbreviation: 'SD' },
  Tennessee: { slug: 'tennessee', abbreviation: 'TN' },
  Texas: { slug: 'texas', abbreviation: 'TX' },
  Utah: { slug: 'utah', abbreviation: 'UT' },
  Vermont: { slug: 'vermont', abbreviation: 'VT' },
  Virginia: { slug: 'virginia', abbreviation: 'VA' },
  Washington: { slug: 'washington', abbreviation: 'WA' },
  'West Virginia': { slug: 'west-virginia', abbreviation: 'WV' },
  Wisconsin: { slug: 'wisconsin', abbreviation: 'WI' },
  Wyoming: { slug: 'wyoming', abbreviation: 'WY' },
};
