name: CSV Validation workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: CSV Validation
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
      - run: npm install
      - run: npm run validate
